sudo: required

services:
  - docker

stages:
  - build
  - publish

jobs:
  include:

    # Job: Build
    - stage: build
      script:
        - docker build -t kopax/gitlab-ci-runner-marathon .
    # Job: Publish
    - stage: publish
      on:
        tags: true
      script:
        - |
          if [[ -z "$TRAVIS_TAG" ]];
            echo "Exiting because not a tag job"
            exit 0
          fi
        - echo "Building and pushing tags ${TRAVIS_TAG}"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t kopax/gitlab-ci-runner-marathon:${TRAVIS_TAG} .
        - docker push kopax/gitlab-ci-runner-marathon:${TRAVIS_TAG}
